monitor.alsa.rules = [
  {
    matches = [
      { "device.name" = "~alsa_card.usb-Audient_Audient_iD4-00.*" }
    ]
    actions = {
      update-props = {
        "device.profile" = "pro-audio"
      }
    }
  },
  {
    matches = [
      { "node.name" = "~alsa_input.usb-Audient_Audient_iD4-00.*" }
    ]
    actions = {
      update-props = {
        "node.description" = "Audient iD4 MKII Input"
        "priority.session" = 1100
        "priority.driver" = 1100
      }
    }
  },
  {
    matches = [
      { "node.name" = "~alsa_output.usb-Audient_Audient_iD4-00.*" }
    ]
    actions = {
      update-props = {
        "node.description" = "Audient iD4 MKII Output"
        "priority.session" = 1100
        "priority.driver" = 1100
      }
    }
  }
]
