monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Sonix_Technology_Co.__Ltd._USB_Live_camera_SN0001-02"
      }
    ]
    actions = {
      update-props = {
         device.disabled = true
      }
    }
  }
]
