[General]
__userfile__=true
icon_follow_color_scheme=true
icon_theme=Papirus-Dark
tool_bar_icon_size=24
tool_button_style=ToolButtonTextBesideIcon

[Palette]
base_color=#191114
highlight_color=#6d3350
highlighted_text_color=#ffd8e7
link_color=#e0bdca
link_visited_color=#feb0d2
text_color=#eedfe3
tooltip_base_color=#191114
tooltip_text_color=#eedfe3
window_color=#191114
window_text_color=#eedfe3

[Qt]
font="Roboto Flex,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
style=qt6ct-style
