-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#191114",
  base01 = "#130c0f",
  base02 = "#21191c",
  base03 = "#504348",
  base04 = "#d4c2c7",
  base05 = "#eedfe3",
  base06 = "#372e31",
  base07 = "#40373a",

  base08 = "#efac82",
  base09 = "#f2bb99",
  base0A = "#e0bdca",
  base0B = "#feb0d2",
  base0C = "#643e24",
  base0D = "#6d3350",
  base0E = "#59404a",
  base0F = "#d09aae",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#6d3350',
  fg = '#ffd8e7', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#e98e55',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9d8d92',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f2bb99',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e0bdca',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#894a68',
})
