[pixdecor]
always_decorate = none
animate = false
# Основной фон заголовка (обычно темный/нейтральный)
bg_color = \{{colors.surface_container_high.default.hex}}FF
# Цвет текста на неактивном фоне
bg_text_color = \{{colors.on_surface_variant.default.hex}}FF
border_size = 7
button_close_image = 
# Цвет кнопок управления (Primary или Accent)
button_color = \{{colors.primary.default.hex}}FF
button_line_thickness = 1.500000
button_maximize_image = 
button_minimize_image = 
button_spacing = 5
button_x_offset = 0
button_y_offset = 0
csd_titlebar_height = 32
# Эффект (например, при наведении), можно оставить красным или взять Error
effect_color = \{{colors.error.default.hex}}FF
effect_type = none
enable_shade = true
# Цвет активного заголовка
fg_color = \{{colors.primary_container.default.hex}}FF
# Цвет текста на активном заголовке
fg_text_color = \{{colors.on_primary_container.default.hex}}FF
ignore_views = none
maximized_borders = false
maximized_shadows = false
overlay_engine = rounded_corners
rounded_corner_radius = 5
shade_duration = 1000ms sigmoid
shade_modifier = <ctrl> <super>
shade_toggle = 
shadow_color = #00000040
shadow_radius = 0
title_font = 
title_text_align = 1
titlebar = true
