theme = "matugen"

[editor]
line-number = "relative"
mouse = true
cursorline = true
bufferline = "always"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "│"
